/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
suma_1_svc(struct Operacion *argp, struct svc_req *rqstp)
{
	static float  result;

	result=argp->num1 + argp->num2;
	return &result;
}

float *
resta_1_svc(struct Operacion *argp, struct svc_req *rqstp)
{
	static float  result;

	
	result=argp->num1 - argp->num2;
	return &result;
}

float *
multiplicacion_1_svc(struct Operacion *argp, struct svc_req *rqstp)
{
	static float  result;

	
	result=argp->num1 * argp->num2;
	return &result;
}

float *
division_1_svc(struct Operacion *argp, struct svc_req *rqstp)
{
	static float  result;
	float ini=1.000;
	int numE1=argp->num1;
	int numE2=argp->num2;
	result=numE1*ini/numE2*ini;
	return &result;
}
