/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host, char *operacion, int nume1, int nume2)
{
	CLIENT *clnt;
	float  *result_1;
	struct Operacion  suma_1_arg = {nume1, nume2};
	float  *result_2;
	struct Operacion  resta_1_arg = {nume1, nume2};
	float  *result_3;
	struct Operacion  multiplicacion_1_arg = {nume1, nume2};
	float  *result_4;
	struct Operacion  division_1_arg = {nume1, nume2};
	//printf("%s %d %d\n",operacion, nume1, nume2);
	//printf("%d %d\n",suma_1_arg.num1, suma_1_arg.num2);
#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if(strcmp(operacion,"suma")==0){
		result_1 = suma_1(&suma_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("El resultado de la suma es: %f\n",*result_1);
		
	}else if(strcmp(operacion,"resta")==0){
		result_2 = resta_1(&resta_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("El resultado de la resta es: %f\n",*result_2);
	}else if(strcmp(operacion,"multiplicacion")==0){
		result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("El resultado de la multiplicacion es: %f\n",*result_3);
	}else if(strcmp(operacion,"division")==0){
		result_4 = division_1(&division_1_arg, clnt);
		if (result_4 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("El resultado de la division es: %f\n",*result_4);
	}else{
		printf("FUNCION INVALIDA\n");
		exit(0);
	}

	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	
	char *host;
	char *operacion = argv[2];
	int num1, num2;
	
	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	num1 = atoi(argv[3]);
	num2 = atoi(argv[4]);
	
	calc_prog_1 (host,operacion, num1, num2);
exit (0);
}
