/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include "rand.h"

void *
inicializa_random_1_svc(long *argp, struct svc_req *rqstp)
{
	
	static char * result;
	long semilla = *argp;
	/*
	 * insert server code here
	 */
	srandom(semilla);
	return (void *) &result;
	//srandom(semilla);
}

long *
obtiene_siguiente_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */
	result=random();
	return &result;
	//return random();
}
