/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operacion {
	int num1;
	int num2;
};
typedef struct Operacion Operacion;

#define CALC_PROG 0x31111111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  float * suma_1(struct Operacion *, CLIENT *);
extern  float * suma_1_svc(struct Operacion *, struct svc_req *);
#define resta 2
extern  float * resta_1(struct Operacion *, CLIENT *);
extern  float * resta_1_svc(struct Operacion *, struct svc_req *);
#define multiplicacion 3
extern  float * multiplicacion_1(struct Operacion *, CLIENT *);
extern  float * multiplicacion_1_svc(struct Operacion *, struct svc_req *);
#define division 4
extern  float * division_1(struct Operacion *, CLIENT *);
extern  float * division_1_svc(struct Operacion *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define resta 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define multiplicacion 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define division 4
extern  float * division_1();
extern  float * division_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operacion (XDR *, Operacion*);

#else /* K&R C */
extern bool_t xdr_Operacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
